# Generated by Django 4.1.2 on 2022-10-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performer', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=60)),
                ('release', models.IntegerField()),
                ('genre', models.CharField(max_length=40)),
            ],
        ),
    ]
